version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
     - 3306:3306
    volumes:
      - ./db.conf:/etc/mysql/conf.d:ro
      - ./db.logs:/var/log/mysql:rw
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    build: ./php-fpm  # Path to the directory containing the Dockerfile for Drupal
    container_name: drupal
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html
      - drupal-files:/var/www/html/web/sites/default/files


  webserver:
    build: ./nginx  # Path to the directory containing the Dockerfile for webserver
    container_name: nginx
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      # - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-files:
  drupal-data:
  db-data:


