version: "3"
services:
  web:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      -  drupal-data:/var/www/drupal
      - ./server.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    networks :
      - external
    depends_on:
      - php
      - mysql

  php:
    build: ./php-fpm
    container_name: php
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/drupal
 
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
     - 3306:3306
    volumes:
      - ./db.conf:/etc/mysql/conf.d:ro
      - ./db.logs:/var/log/mysql:rw
      - db-data:/var/lib/mysql
    networks:
      - internal

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data:
  db-data:
