# Dockerfile for webserver service
FROM nginx:1.25.5-alpine

# Copy custom Nginx configuration files
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY default.conf /etc/nginx/conf.d/default.conf

# Expose port 80 if needed
# EXPOSE 80

# Set any additional environment variables if needed
# ENV EXAMPLE_VARIABLE=value

# Set entrypoint or default command if needed
# ENTRYPOINT ["nginx"]
# CMD ["-g", "daemon off;"]
